import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import MainSection from "../components/MainSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>HaggleX Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div>
        <Header />
      </div>
      <div className="flex flex-grow-">
        <Sidebar />
        <MainSection />
      </div>
    </div>
  );
}
