import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>HaggleX Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to HaggleX Web Application</h1>
      {/* Header */}
      <div>
        <h1>Header</h1>
      </div>
      {/* Sidebar */}
      <div>
        <h1>Sidebar</h1>
      </div>
      {/* Main Section */}
      <div>
        <h1>Main Section</h1>
      </div>
    </div>
  )
}
